## spring.application.name=oms-user-service
 ## jdbc:postgresql://postgres-product:5432/oms_product_db

server:
  port: 8081

spring:
  application:
    name: oms-user-service
  datasource:
    url: jdbc:postgresql://postgres-user:5432/oms_user_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: my-super-secret-key-oms-project-2026
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans