## spring.application.name=oms-user-service


server:
  port: 8081

spring:
  application:
    name: oms-user-service
  datasource:
    url: jdbc:postgresql://localhost:5433/oms_user_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: my-super-secret-key-oms-project-2026
  expiration: 86400000